server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - StripPrefix=0
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs