### Creates a new patient entity
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
    "name": "Rohit Sharma",
    "email": "hitman@example.com",
    "address": "125 Main St, Bandra, Mumbai",
    "dateOfBirth": "1990-01-01",
    "registeredDate": "2022-01-01"
}

###